version: 2
snapshot:
  widths:
    - 375  # Mobile
    - 768  # Tablet
    - 1280 # Desktop
  min-height: 1024
  enable-javascript: true
  wait-for-timeout: 30000
  wait-for-selector: 'body'

# Percy configuration for visual regression testing
static:
  include: '**/*.html'
  exclude: 
    - '**/node_modules/**'
    - '**/dist/**'

# Discovery
discovery:
  allowed-hostnames:
    - localhost
    - '*.lovable.app'
  
  network-idle-timeout: 750

# CI specific settings  
ci:
  build-dir: dist
